# Generated by Django 4.2.5 on 2023-10-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiniapp', '0002_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Catogory_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
