# Generated by Django 4.2.5 on 2023-10-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='logindb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginus', models.CharField(blank=True, max_length=100, null=True)),
                ('loginpwd', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
